GET http://localhost:3000/products

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "title": "Cashewmilch",
    "imgpath": "images/09.png",
    "price": "200"
}

###

POST http://localhost:3000/cart
Content-Type: application/json

{
    "productid": "KNaPVUV7deZ8jxnO",
    "userid": "123456789"
}

###

GET http://localhost:3000/cart
Content-Type: application/json

{
    "userid": "123456789"
}

###

GET http://localhost:3000/invoices

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "value": 50,
    "payed": true,
    "date": "07.11.2021",
    "time": "07:11",
    "status": "ordered",
    "address": {
        "street": "Hauptstraße",
        "streetnr": "1",
        "zipcode": "12345",
        "city": "Berlin",
        "name": "Hans Meier"
    },
    "products": [
        {"title":"Cashewmilch","price":2,"quantity":3},
        {"title":"Lupinenmilch","price":2,"quantity":1},
        {"title":"Sojamilch","price":2,"quantity":1},
        {"title":"Hanfmilch","price":2,"quantity":2},
        {"title":"Hafermilch","price":2,"quantity":1},
        {"title":"Haselnussmilch","price":2,"quantity":2},
        {"title":"Reismilch","price":2,"quantity":3},
        {"title":"Dinkelmilch","price":2,"quantity":5},
        {"title":"Mandelmilch","price":2,"quantity":7}
    ]
}

###

GET http://localhost:3000/orders

###